### ISSUE TITLE
Prepare questions for meeting

### ISSUE THREAD

**Issue by jbendsen** [jypma/LB3210#10]
We need to prepare a few questions for our meeting with Hans.

Some ideas for questions:

1. Give a description of the attendees in terms of their experience regarding:
- Java
- Spring and Spring Boot
- Functional programming style, and Java Lambdas
- Java versions > 8
2. Do they have any experience with microservices?
3. Are they familiar with REST and Web APIs?
4. Are they used to working with IT architecture? 
5. What are their experience levels: <5 years, 5-10 years, 10+ years (or another suitable scale)

**Comment by jbendsen** [comment]
Fra Jans mail:
- Erfaring med konkrete Java frameworks
- Forventning til undervisning af (andre) konkrete Java frameworks
- Chancer for fysisk("hybrid") eller helt-virtuelt
- Teknisk værktøj til virtuelt møde (gather, whiteboards i gather,
  slack)
- Hvilken hardware har folk (RAM, OS, webbrowser, restriktioner)

**Comment by jypma** [comment]
Agreed to take these notes offline.
