### ISSUE TITLE
Demo project needs PUT and POST resources

### ISSUE THREAD

**Issue by jypma** [jypma/LB3210#2]
The `GET` resource is there, and serves up manually-inserted database content.

We need to extend on this a bit:
- [x] Create a database migration that adds an (integer) primary key to the demo table (and see how we tie that auto-generated key into JOOQ)
- [x] Create REST API `POST /values` , with a JSON body having a `key` and `value`, returning a 201 Created and a Location header
- [x] Create `PUT /values/42`, with the same JSON body structure, to replace an earlier value.

**Comment by jbendsen** [comment]
I think the new methods in DemoRepository can be rewritten in a more functional style.

**Comment by jypma** [comment]
Methods have been added now.
