### ISSUE TITLE
Describe bulkhead with SVG picture

### ISSUE THREAD

**Issue by jypma** [jypma/LB3210#5]
As described [here](https://resilience4j.readme.io/docs/bulkhead), but with an UML sequence diagram.

For UML sequence diagram, use PlantUML.

**Comment by jbendsen** [comment]
@jypma, I've made a demo of how to use plantuml and markdown to generate diagrams. See [demo-uml.md](https://github.com/jypma/LB3210/blob/master/graphics/plant-uml/demo-uml.md). Is this a useful way of making diagrams, and will it fit into the slides in a seamless way?

**Comment by jbendsen** [comment]
I've made a first draft of illustrations for bulkhead [here](https://github.com/jypma/LB3210/tree/master/graphics/svg). It is partly inspired by this: [ youtube clip](https://www.youtube.com/watch?v=R2FT5edyKOg).

**Comment by jypma** [comment]
I'm intending to embed the plantuml into the .org file as described [here](https://plantuml.com/zh/emacs). But any separate file is OK.

Can I suggest we review each other's suggestions before merging them into `master` though? That way it's easier to track what's under development.

**Comment by jypma** [comment]
* bulkhead1.svg: 
  - Can you split this into 2 SVGs? That way we can have them on 2 slides
  - Remove the green background from slide 2
  - Remove the titles from the pictures, I think the title is better put on the slide itself
* bulkhead2.svg: 
  - Nice idea :) but I think I'd either skip over this, or put a real ship picture in if we need to explain the (linguistic) term "bulkhead"... what do you think?

**Comment by jypma** [comment]
Bulkhead is incorporated now.
